services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  pulsar:
    image: apachepulsar/pulsar
    command: >
      /pulsar/bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080 # Pulsar admin portu
      - 2181:2181 # ZooKeeper
      - 3181:3181 # BookKeeper

